version: '3.8'

services:
  aqi-predictor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: aqi-predictor
    ports:
      - "8501:8501"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - AQICN_API_KEY=${AQICN_API_KEY}
      - WEATHERAPI_API_KEY=${WEATHERAPI_API_KEY}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database service for production
  # postgres:
  #   image: postgres:13
  #   container_name: aqi-predictor-db
  #   environment:
  #     - POSTGRES_DB=aqi_predictor
  #     - POSTGRES_USER=aqi_user
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data: 